name: arbigent-test

on:
  push:
    branches:
      - main
    tags:
      - '**'
  pull_request:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx6g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  ARBIGENT_VERSION: "0.3.0"

permissions:
  contents: write

jobs:
  cli-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Delete unnecessary tools 🔧
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: false # Don't remove Android tools
          tool-cache: true # Remove image tool cache - rm -rf "$AGENT_TOOLSDIRECTORY"
          dotnet: true # rm -rf /usr/share/dotnet
          haskell: true # rm -rf /opt/ghc...
          swap-storage: true # rm -f /mnt/swapfile (4GiB)
          docker-images: false # Takes 16s, enable if needed in the future
          large-packages: false # includes google-cloud-sdk and it's slow

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Download arbigent
        run: |
          wget https://github.com/takahirom/arbigent/releases/download/${{ env.ARBIGENT_VERSION }}/arbigent-${{ env.ARBIGENT_VERSION }}.zip
          unzip arbigent-${{ env.ARBIGENT_VERSION }}.zip

      - name: CLI E2E test
        uses: reactivecircus/android-emulator-runner@v2
        env:
          MOSAIC_RAW_MODE: false
          GEMINI_API_KEY: ${{ secrets.GEMINI_FREE_API_KEY }}
        with:
          api-level: 34
          arch: x86_64
          disable-animations: true
          disk-size: 6000M
          heap-size: 600M
          script: |
            arbigent-${{ env.ARBIGENT_VERSION }}/bin/arbigent --os=android --scenario-file=arbigent-test.yaml --ai-type=gemini --gemini-model-name=gemini-2.0-flash-exp

      - uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        if: ${{ always() }}
        with:
          name: cli-report
          path: |
            arbigent-result/*
          retention-days: 120